# Generated by Django 2.2.6 on 2019-12-13 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('internationalization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='map_bounds',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='internationalization.LatLngBounds'),
        ),
    ]
