# Generated by Django 3.0.2 on 2020-01-29 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internationalization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='latlngbounds',
            name='name',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
