# Generated by Django 3.0.2 on 2020-02-04 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internationalization', '0002_latlngbounds_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='calling_code',
            field=models.CharField(default='', max_length=9),
        ),
    ]
