# Generated by Django 3.0.3 on 2020-02-18 20:50

import corexen.utils.models
import django.contrib.postgres.fields.citext
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('internationalization', '0003_country_calling_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='code',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='geo_code_json',
            field=corexen.utils.models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations', to='internationalization.City'),
        ),
        migrations.AddField(
            model_name='city',
            name='type',
            field=models.CharField(choices=[('locality', 'Locality'), ('administrative_area_level_1', 'Administrative Area Level 1'), ('administrative_area_level_2', 'Administrative Area Level 2'), ('administrative_area_level_3', 'Administrative Area Level 3'), ('administrative_area_level_4', 'Administrative Area Level 4'), ('administrative_area_level_5', 'Administrative Area Level 5')], default='locality', max_length=60),
        ),
        migrations.AddField(
            model_name='country',
            name='administrative_area_level',
            field=models.IntegerField(choices=[(1, 'Administrative Area Level 1'), (2, 'Administrative Area Level 2'), (3, 'Administrative Area Level 3'), (4, 'Administrative Area Level 4'), (5, 'Administrative Area Level 5')], default=2),
        ),
        migrations.AddField(
            model_name='country',
            name='administrative_area_level_1_name',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='administrative_area_level_2_name',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='administrative_area_level_3_name',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='administrative_area_level_4_name',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='administrative_area_level_5_name',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='flag',
            field=models.ImageField(upload_to=corexen.utils.models.RandomFileName('locations/images/')),
        ),
        migrations.AlterField(
            model_name='city',
            name='google_map_key',
            field=django.contrib.postgres.fields.citext.CICharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterUniqueTogether(
            name='city',
            unique_together={('country', 'code')},
        ),
    ]
