# Generated by Django 3.0.3 on 2020-02-07 15:56

import corexen.utils.models
import django.contrib.postgres.fields.citext
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internationalization', '0003_country_calling_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('flag', models.ImageField(upload_to=corexen.utils.models.RandomFileName('locations/images/'))),
                ('code', models.IntegerField()),
                ('type', models.CharField(choices=[('locality', 'Locality'), ('administrative_area_level_1', 'Administrative Area Level 1'), ('administrative_area_level_2', 'Administrative Area Level 2'), ('administrative_area_level_3', 'Administrative Area Level 3'), ('administrative_area_level_4', 'Administrative Area Level 4'), ('administrative_area_level_5', 'Administrative Area Level 5')], default='locality', max_length=60)),
                ('google_map_key', django.contrib.postgres.fields.citext.CICharField(max_length=150, unique=True)),
                ('geo_code_json', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.RemoveField(
            model_name='city',
            name='country',
        ),
        migrations.RemoveField(
            model_name='city',
            name='map_bounds',
        ),
        migrations.AddField(
            model_name='country',
            name='administrative_area_level',
            field=models.IntegerField(choices=[(1, 'Administrative Area Level 1'), (2, 'Administrative Area Level 2'), (3, 'Administrative Area Level 3'), (4, 'Administrative Area Level 4'), (5, 'Administrative Area Level 5')], default=2),
        ),
        migrations.AddField(
            model_name='country',
            name='administrative_area_level_1_name',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='administrative_area_level_2_name',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='administrative_area_level_3_name',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='administrative_area_level_4_name',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='administrative_area_level_5_name',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
    ]
