# Generated by Django 3.0.3 on 2020-02-25 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internationalization', '0004_auto_20200225_1358'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LatLngBounds',
        ),
    ]
