# Generated by Django 3.0.3 on 2020-02-10 16:50

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('internationalization', '0004_auto_20200210_1650'),
        ('companies', '0006_auto_20200210_1650'),
    ]

    operations = [
        migrations.DeleteModel(
            name='City',
        ),
        migrations.AddField(
            model_name='locationarea',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='internationalization.Country'),
        ),
        migrations.AddField(
            model_name='locationarea',
            name='map_bounds',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='internationalization.LatLngBounds'),
        ),
        migrations.AddField(
            model_name='locationarea',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations', to='internationalization.LocationArea'),
        ),
        migrations.AlterUniqueTogether(
            name='locationarea',
            unique_together={('country', 'code')},
        ),
    ]
