# Generated by Django 3.0.3 on 2020-02-26 22:15

import corexen.utils.models
import corexen.utils.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internationalization', '0005_delete_latlngbounds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='bounds',
            field=corexen.utils.models.JSONField(blank=True, null=True, validators=[corexen.utils.validators.JSONSchemaValidator(limit_value={'$schema': 'https://json-schema.org/schema#', 'properties': {'northeast': {'properties': {'lat': {'type': 'number'}, 'lng': {'type': 'number'}}, 'required': ['lat', 'lng'], 'type': 'object'}, 'southwest': {'properties': {'lat': {'type': 'number'}, 'lng': {'type': 'number'}}, 'required': ['lat', 'lng'], 'type': 'object'}}, 'required': ['northeast', 'southwest'], 'type': 'object'})]),
        ),
    ]
