# Generated by Django 3.0.3 on 2020-04-06 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internationalization', '0006_auto_20200226_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='zoom_desktop',
            field=models.IntegerField(default=14),
        ),
        migrations.AddField(
            model_name='city',
            name='zoom_mobile',
            field=models.IntegerField(default=13),
        ),
    ]
