# Generated by Django 3.2.18 on 2023-04-14 12:59

import corexen.utils.models
import corexen.utils.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internationalization', '0007_auto_20200406_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='bounds',
            field=corexen.utils.models.JSONField(null=True, blank=True, validators=[corexen.utils.validators.JSONSchemaValidator(limit_value={'$schema': 'https://json-schema.org/schema#', 'properties': {'northeast': {'properties': {'lat': {'type': 'number'}, 'lng': {'type': 'number'}}, 'required': ['lat', 'lng'], 'type': 'object'}, 'southwest': {'properties': {'lat': {'type': 'number'}, 'lng': {'type': 'number'}}, 'required': ['lat', 'lng'], 'type': 'object'}}, 'required': ['northeast', 'southwest'], 'type': 'object'})]),
        ),
        migrations.AlterField(
            model_name='city',
            name='geo_code_json',
            field=corexen.utils.models.JSONField(null=True, blank=True),
        ),
    ]
