# Generated by Django 3.2.18 on 2024-06-19 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internationalization', '0008_auto_20230414_0759'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='iso_code',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
