version: '3.7'

services:
  corexen_develop.django:
    image: corexen
    build:
      context: .
      dockerfile: ./compose/develop/django/Dockerfile
    command: "/start"
    volumes:
      - .:/app
    ports:
      - 8000:8000

