version: '3.7'

volumes:
  corexen_develop_postgres_data: {}

services:
  corexen_develop.django:
    image: corexen
    build:
      context: .
      dockerfile: ./compose/develop/django/Dockerfile
    volumes:
      - .:/app

