# Generated by Django 2.2.6 on 2019-10-29 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_banned',
            field=models.BooleanField(default=False, help_text='Designate if this user should be treated as banned', verbose_name='banned'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_enabled',
            field=models.BooleanField(default=True, help_text='Designate if this user should be treated as enabled', verbose_name='enabled'),
        ),
    ]
