# Generated by Django 2.2.4 on 2019-12-16 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verified_at',
            field=models.DateTimeField(blank=True, help_text='Date time on which the email was verified.', null=True, verbose_name='email_verified_at'),
        ),
        migrations.AddField(
            model_name='user',
            name='non_verified_email',
            field=models.EmailField(blank=True, help_text='Verified email. This field is not used by all user profiles.', max_length=254, null=True, verbose_name='non_email_address'),
        ),
        migrations.AddField(
            model_name='user',
            name='non_verified_phone_number',
            field=models.CharField(blank=True, help_text='Non verified phone number. 26 digits or fewer.', max_length=26, null=True, verbose_name='non_verified_phone_number'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Verified phone number. 26 digits or fewer.', max_length=26, null=True, verbose_name='phone_number'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number_verified_at',
            field=models.DateTimeField(blank=True, help_text='Date time on which the phone number was verified.', null=True, verbose_name='phone_number_verified_at'),
        ),
    ]
