# Generated by Django 3.0.2 on 2020-02-19 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_auto_20200129_1553'),
        ('auth', '0011_update_proxy_permissions'),
        ('users', '0003_user_verification_code'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userpermission',
            unique_together={('user', 'permission', 'headquarter')},
        ),
    ]
