# Generated by Django 2.2.5 on 2019-09-09 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_appuser_is_active'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AppUser',
        ),
    ]
