# Generated by Django 2.2.4 on 2019-08-29 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '__latest__'),
        ('users', '0004_remotepermissionsmixin'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='appuser_set', related_query_name='remoteuser', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='appuser',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='appuser_set', related_query_name='appuser', through='users.UserPermission', to='auth.Permission', verbose_name='user permissions'),
        ),
        migrations.DeleteModel(
            name='RemotePermissionsMixin',
        ),
    ]
