# Generated by Django 2.2.4 on 2019-08-20 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_headquarter_is_deleted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={},
        ),
        migrations.AlterModelOptions(
            name='headquarter',
            options={},
        ),
        migrations.AddField(
            model_name='company',
            name='created_by',
            field=models.UUIDField(null=True),
        ),
    ]
