# Generated by Django 2.2.4 on 2019-08-20 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_auto_20190820_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='headquarter',
            name='created_by',
            field=models.UUIDField(null=True),
        ),
    ]
