# Generated by Django 3.0 on 2019-12-16 21:43

import corexen.utils.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('internationalization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nit', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('email', models.EmailField(max_length=100)),
                ('image_url', models.ImageField(upload_to=corexen.utils.models.RandomFileName('companies/images/'))),
                ('namespace', models.CharField(max_length=60, unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Headquarter',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('image_url', models.ImageField(upload_to=corexen.utils.models.RandomFileName('headquarters/images/'))),
                ('email', models.EmailField(max_length=100, null=True)),
                ('phone', models.CharField(max_length=30, null=True)),
                ('address', models.CharField(max_length=120)),
                ('neighborhood', models.CharField(blank=True, max_length=120, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='headquarters', to='internationalization.City')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='companies.Company')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
