# Generated by Django 2.2.4 on 2019-08-28 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='image_url',
            field=models.ImageField(default='default.png', upload_to='companies/images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='headquarter',
            name='image_url',
            field=models.ImageField(default='default.jpg', upload_to='headquarters/images/'),
            preserve_default=False,
        ),
    ]
