# Generated by Django 2.2.4 on 2019-09-13 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_auto_20190911_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='headquarter',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
