# Generated by Django 2.2.4 on 2019-08-30 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_auto_20190829_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headquarter',
            name='city',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='headquarter',
            name='country',
            field=models.CharField(max_length=50),
        ),
    ]
