# Generated by Django 2.2.6 on 2019-10-25 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_auto_20191002_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='namespace',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
