# Generated by Django 3.0 on 2019-12-21 21:16

import django.contrib.postgres.fields.citext
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internationalization', '0001_initial'),
        ('companies', '0002_auto_20191216_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='name',
            field=django.contrib.postgres.fields.citext.CICharField(max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='headquarter',
            name='name',
            field=django.contrib.postgres.fields.citext.CICharField(max_length=120),
        ),
        migrations.AlterUniqueTogether(
            name='headquarter',
            unique_together={('name', 'company'), ('name', 'city')},
        ),
    ]
