# Generated by Django 3.0 on 2020-01-07 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_auto_20191221_2116'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='headquarter',
            unique_together=set(),
        ),
    ]
