# Generated by Django 2.2.6 on 2019-10-29 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_company_namespace'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ('-created_at', '-updated_at')},
        ),
        migrations.AlterModelOptions(
            name='headquarter',
            options={'ordering': ('-created_at', '-updated_at')},
        ),
        migrations.RemoveField(
            model_name='headquarter',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='headquarter',
            name='recruitment',
        ),
        migrations.RemoveField(
            model_name='headquarter',
            name='recruitment_message',
        ),
    ]
