# Generated by Django 2.2.4 on 2019-08-31 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_auto_20190830_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='country',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='headquarter',
            name='phone',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
