# Generated by Django 3.0.2 on 2020-01-29 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_auto_20200107_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='headquarter',
            name='latitude',
            field=models.DecimalField(decimal_places=15, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='headquarter',
            name='longitude',
            field=models.DecimalField(decimal_places=15, default=0, max_digits=18),
        ),
    ]
