# Generated by Django 2.2.4 on 2019-12-03 22:27

import corexen.utils.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_auto_20191029_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='image_url',
            field=models.ImageField(upload_to=corexen.utils.models.RandomFileName('companies/images/')),
        ),
        migrations.AlterField(
            model_name='headquarter',
            name='image_url',
            field=models.ImageField(upload_to=corexen.utils.models.RandomFileName('headquarters/images/')),
        ),
    ]
