# Generated by Django 3.0.3 on 2020-02-10 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('internationalization', '0004_auto_20200210_1650'),
        ('companies', '0005_auto_20200129_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headquarter',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='headquarters', to='internationalization.LocationArea'),
        ),
    ]
