# Generated by Django 2.2.4 on 2019-09-05 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_auto_20190902_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='headquarter',
            name='recruitment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='headquarter',
            name='recruitment_message',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
