# Generated by Django 3.0.3 on 2020-06-27 23:34

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_headquarter_google_key'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='company',
            managers=[
                ('default_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='headquarter',
            managers=[
                ('default_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='headquarter',
            name='is_deleted',
        ),
        migrations.AddField(
            model_name='company',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='headquarter',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
