# Generated by Django 3.0.3 on 2020-06-26 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_headquarter_google_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='headquarter',
            name='is_deleted',
        ),
        migrations.AddField(
            model_name='company',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='headquarter',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
